namespace ModeManager;

internal enum MessageKey
{
    // Plugin lifecycle / logs
    LogPluginLoaded,
    LogPluginUnloaded,
    LogLanguageSet,
    LogInitialModeQueued,
    LogInitialModeKeyNotFound,
    LogInitialModeScheduled,
    LogDynamicCommandsRegistered,
    LogConfigReloaded,
    LogReloadConfigNotFound,
    LogReloadException,
    LogSwitchScheduled,
    LogPendingCanceled,
    LogSwitcherNotInitialized,
    LogApplyingMode,
    LogModeApplied,
    LogModeApplyFailed,
    LogResetCfgCreated,
    LogResetCfgCreateFailed,
    LogEndMatchMapVoteSyncSuccess,
    LogEndMatchMapVoteSyncFailed,
    LogEndMatchMapVoteSyncSkipped,
    LogMenuApiAvailable,
    LogMenuApiMissing,

    // Command descriptions
    CmdDescHelp,
    CmdDescModes,
    CmdDescSetMode,
    CmdDescRtv,
    CmdDescReload,
    CmdDescDynamicMode,

    // Chat formatting
    ChatPrefix,

    // Help / command replies
    HelpTitle,
    HelpCommandsLabel,
    HelpLineMm,
    HelpLineModes,
    HelpLineSetMode,
    HelpLineRtv,
    HelpLineDynamicMode,
    HelpLineReload,
    HelpModesList,
    ModesListInfo,
    ModesVoteHint,
    ErrorSetModeUsage,
    ErrorModeNotFound,
    ModeNoPermission,
    MenuOpenFailed,
    MenuTitleModes,
    MenuTitleMaps,
    MenuTitleConfirm,
    MenuOptionConfirmVote,
    MenuOptionBackToMaps,
    RtvMenuOpened,
    RtvDisabled,
    RtvToggleUsage,
    RtvToggleNoPermission,
    RtvToggleEnabled,
    RtvToggleDisabled,

    // Voting
    VoteConsoleScheduled,
    ErrorInvalidPlayer,
    VotePendingAlready,
    VoteCooldown,
    VoteIneligible,
    VoteIdentityMissing,
    VoteAlreadyActiveMode,
    VoteAnotherModeInProgress,
    VoteMinPlayers,
    VoteMapSelectionInvalid,
    VoteMapSelectionAvailableMaps,
    VoteStartedChat,
    VoteRegisteredSelf,
    VoteAlreadyCast,
    VoteStatusAlreadyVoted,
    VoteRegisteredChat,
    VoteExpiredChat,

    // Switching
    SwitchApprovedNow,
    SwitchApprovedIn,
    ChatSwitcherNotInitialized,
    ChatModeChanged,
    ChatModeApplyFailed,

    // Config reload
    ReloadNoPermission,
    ReloadConfigSuccess,
    ReloadConfigNotFound,
    ReloadCommandsRebuilt,
    ReloadUseHelp,
    ReloadFailed,

    // Loader / validator
    LoaderConfigNotFound,
    LoaderDeserializeNull,
    ValidationLanguageUnsupported,
    ValidationModesRequired,
    ValidationResetCommandRequired,
    ValidationVoteRatioRange,
    ValidationVoteMinPlayersRange,
    ValidationVoteDurationRange,
    ValidationSwitchCooldownRange,
    ValidationSwitchDelayRange,
    ValidationEndMatchMapVoteFileRequired,
    ValidationEndMatchMapVoteMapgroupPrefixInvalid,
    ValidationEndMatchMapVoteFileNotFound,
    ValidationModeNull,
    ValidationExecCommandRequired,
    ValidationPluginToLoadNotFound,
    ValidationSelfUnloadForbidden,
    ValidationDynamicCommandConflictsBase,
    ValidationDynamicCommandCollision,
    ValidationDefaultMapInvalid,
    ValidationMapPoolMapInvalid,
    ValidationGameTypeInvalid,
    ValidationGameModeInvalid,

    // Startup chat
    ChatInitialModeScheduled
}
